title: "100行のPythonから育てて原理を学ぶ プログラミング言語の作り方"
summary: |
  ※執筆途中のドラフト状態で公開していますので修正が入ります。ご了承ください。

  「PythonやRubyみたいなプログラミング言語って、中はどう動いているんだろう？」
  「言語を自作するのって面白そうだけど、難しいんだろうな」

  そんな風に思っている方に読んでみていただきたい「プログラミング言語の作り方」超入門です。前作『350行くらいのPythonで作るプログラミング言語実装超入門』と同様のコンセプトですが、開発の進め方・実装方法を見直し、より楽しく、より深く学べるものになっています。
  
  本書の狙いは、小さい小さい（プログラミング言語とは思えないような）言語からスタートし、少しずつ機能を追加しては動かす、を繰り返しているうちにいつのまにか原理が身についている、というものです。

  本書には以下の三つの特徴があります。

  1. Pythonの基礎知識のみで始められる
  ソースコードは純粋にPythonのみで書かれており、Pythonの知識ですべて理解できます。便利なライブラリやツールは用いずに自分ですべて書いていくため、しくみを自ら体験しながら学べます。
  
  2. どの章で読み終わってもまとまった学びが得られる
  ほんの数行のプログラムから始めて、節ごとに機能を追加しては動かして試します。第 1 章の終わりには変数・制御構造・関数定義といった最小限の機能を持つインタプリタのコア部分が完成します。第2章でも同様に進めてインタプリタに仕立て上げます。3章では コア部分に現代のインタプリタの主流である「コンパイラ＋仮想マシン」の構成を取り入れます。その後も章ごとに機能を拡張し、最終的にはパターンマッチやマクロ、JIT（もどき）といった機能を持つインタプリタができます。このように、最後まで進まないとインタプリタが動かないといったことはなく、どの章で読むのをやめてもまとまった学びを得ることができます。

  3. コンパクトなプログラムで理解しやすい
  第 1 章で書くインタプリタのコアは 100 行程度、第 2 章でインタプリタになったところで 300 行程度、第 3 章終了時点で 500 行程度と、プログラムがコンパクトなため自作プログラミング言語は初めてという方にも無理なく全体を把握することができます。すべてのコードが紙面に記載されているので、エディタでソースコードを参照しつつ・・・としなくても読めるようになっています。最終的には1,500行くらいになりますが、一度に追加するのはせいぜい数十行なのであまり長さを感じることはなく、いつのまにか 1,500行になっていた、という感じで読み進められるのではないかと思います。

  プログラムをコンパクトにするために切り捨てた部分（エラー処理・堅牢性・性能など）も多いですが、大事な用語や概念はとりあげるようにしていますので、より深く学びたくなったとき本格的な書籍に取り組むための土台にもなるはずです。

  とは言いうものの、文章はかなりユルい感じで書いていますので、気軽に読み始めてみてください。ご質問・ご指摘などありましたらぜひ下の方にある「読者コミュニティ」でコメントお願いします！

topics: ["Python", "自作言語", "インタプリタ", "プログラミング言語", "言語処理系"]
published: false
price: 0
toc_depth: 2
