title: "育てて学ぶ はじめての自作プログラミング言語"
summary: |
  ※執筆途中のドラフト状態ですが第 1 部まで書いたので公開しています。
  ※そのため、今後修正が入る可能性があります。ご了承ください。

  「Python や Ruby みたいなプログラミング言語って、中はどう動いているんだろう？」
  「言語を自作するのって面白そうだけど、難しいんだろうな」

  そんな風に思っている方に読んでみていただきたい「プログラミング言語の作り方」超入門です。
  
  本書の狙いは、小さい小さい（プログラミング言語とは思えないような）言語からスタートし、少しずつ機能を追加しては動かす、を繰り返しているうちにいつのまにかプログラミング言語が作れるようになっている、というものです。

  本書には以下の三つの特徴があります。

  1. Python の基礎知識のみで始められる
  ソースコードは純粋に Python のみで書かれており、Python の知識ですべて理解できます。便利なライブラリやツールは用いずに自分ですべて書いていくため、しくみを自ら体験しながら学べます。プログラミング言語処理系にはいろいろなプログラミングのエッセンスが詰まっていますし、処理系の動作を知ることにより言語自体の理解も深まりますので、Python が書けるようになってきたから次へステップアップしたい、という方の学習対象としてもお勧めします。

  2. どの章で読み終わってもまとまった学びが得られる
  ほんの数行のプログラムから始めて、節ごとに機能を追加しては動かして試します。第 1 章の終わりには変数・制御構造・関数定義といった最小限の機能を持つインタプリタのコア部分が完成します。第 2 章ではテキストを読み込む機能（字句解析・構文解析）を追加して本物のインタプリタに仕立て上げます。第 3 章ではコア部分に現代のインタプリタの主流である「コンパイラ＋仮想マシン」の構成を取り入れて動かします。このように、最後まで読まないとプログラミング言語が完成しないといったことはなく、どの章で読むのをやめてもまとまった学びを得ることができます。

  3. コンパクトなプログラムで理解しやすい
  第 1 章で書くインタプリタのコアは 100 行程度、第 2 章でインタプリタになったところで 350 行程度、第 3 章終了時点で 500 行程度と、プログラムがコンパクトなため自作プログラミング言語は初めてという方にも無理なく全体を把握することができます。すべてのコードが紙面に記載されているので、エディタでソースコードを参照しつつ・・・としなくても読めるようになっています。（未公開の部分を含め）最終的には 1,500 行くらいになりますが、一度に追加するのはせいぜい数十行なのであまり長さを感じることはなく、いつのまにか 1,500 行になっていた、という感じで読み進められるのではないかと思います。

  プログラムをコンパクトにするために切り捨てた部分（エラー処理・堅牢性・性能など）も多いですが、大事な用語や概念はとりあげるようにしていますので、より深く学びたくなったとき本格的な書籍に取り組むための土台にもなるはずです。

  文章も堅苦しくならないよう、リラックスした感じで書いていますので、気軽に読み始めてみてください。ご質問・ご指摘などありましたらぜひ下の方にある「読者コミュニティ」でコメントお願いします！

topics: ["Python", "自作言語", "インタプリタ", "プログラミング言語", "言語処理系"]
published: false
price: 0
toc_depth: 2
