title: "100行のPythonから育てて原理を学ぶ プログラミング言語の作り方"
summary: |
  ※執筆途中のドラフト状態で公開していますので修正が入ります。ご了承ください。

  『350行くらいのPythonで作るプログラミング言語実装超入門』に続き、PythonとかRubyとかプログラミング言語って中はどうなってるの？なんか面白そうだけど難しいんじゃ？と思っている方へと思って書いた本第2弾です。当初は『350行（以下略）第2版』のつもりだったのですが全く別モノになったのでタイトルから変更しました。

  第1章では100行程度のコードでインタプリタのコア部分（評価器）を作り、アルゴリズムを実行できるようにします。ここだけ読んでも大きな学びになります。これが第1部の終わりでは字句解析・構文解析を持ったインタプリタ（500行程度）に育ち、ツリーウォーク型・中間コードインタプリタ型のふたつの原理を体験します。

  その後も少しずつインクリメンタルに機能を足しては動かすことを繰り返し、最終的にはわりとモダンな機能を持った言語になります。この時点では1,500行くらいのコードになっていますが、一度に追加するのはせいぜい数十行なのであまり長さを感じることはないと思います。

  パターンマッチやマクロ、カスタム文法のような自作言語入門系の書籍では取り上げられることの少ない機能まで触れているのも本書の特徴です。

  どの章で読み終わっても学びや達成感があるように書いていますので、気軽に読み始めてみてください。ご質問・ご指摘などありましたらぜひ下の方にある「読者コミュニティ」でコメントお願いします！

topics: ["Python", "自作言語", "インタプリタ", "プログラミング言語", "言語処理系"]
published: false
price: 0
toc_depth: 2
