title: "350行くらいのPythonで作るプログラミング言語実装超入門"
summary: |
  PythonとかRubyとかプログラミング言語って中はどうなってるの？なんか面白そうだけど難しいんじゃ？と思っている方へと思って書きました。

  短いコードでプログラミング言語実装の基本を学べるよう、機能は最小限にしぼっていますが、見た目はまあまあ普通のプログラミング言語を作ります。技巧を駆使してコードを短くした、というものではなく普通に書いてありますので、Pythonの基本的なところがわかっていれば読むのにそれほど苦労はしないと思います。

  コードが短いのではじめてプログラミング言語実装の勉強をする人でも全体を把握することができます。また機能が最小限と言うことは機能を追加する余地も大きいということですので、自分で拡張することも比較的容易です。読んだ後、350行で書けるなら自分で１から書いてみるか！とか、よしもっと本格的な本読んでみるか！などと思っていただけたら望外の喜びです。

  ご質問・ご指摘などありましたら下の方にある「読者コミュニティ」へお願いします。
topics: ["computerscience", "language", "interpreter", "python", "minilang"]
published: true
price: 0 
toc_depth: 1
