title: "350行くらいのコードでコンパクトだけどまあまあ普通なインタプリタを書いてみる"
summary: "インタプリタとかコンパイラとかいわゆる言語処理系って中はどうなってるの？なんか面白そうだけど難しいんじゃ？と思っている方へ"
topics: ["computerscience", "language", "interpreter", "minilang"]
published: false
price: 0 
toc_depth: 1
