volumes:
  node_modules:


services:
  zenn-content:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    container_name: 'devcon_zenn-content'
    stdin_open: true
    tty: true
    working_dir: /workspaces/zenn-content
    volumes:
      - ..:/workspaces/zenn-content
      - node_modules:/workspaces/zenn-content/node_modules
