title: "350行くらいのPythonでインタプリタを書いてみる"
summary: "プログラミング言語ってどうやって動いてるんだろう？おもしろそうだけどなんか難しそう、という方へ。ちょっとしたインタプリタを書く"
topics: ["コンピュータサイエンス", "言語処理系", "プログラミング言語", "インタプリタ", "Computer Science", "Language Processor", "Programming Language", "Interpreter"]
published: false
price: 0 
chapters:
  - introduction
  - specification
  - print
  - scanner-parser-evaluator
  - preparation
  - expression
  - boolean
  - variable-scope
  - control
  - function
  - conclusion
  - interpreter-in-50-lines
  - references
  - binary-search-tree
  - interpreter-in-150-lines
  - source
  